gps_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "gps"
      manager_ip: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    transform: [0.0, 0.0, 0.21, 0.0, 0.0, 0.0]
    intensity: False

    frame_id: "gps"
    topic_name: "navsatfix"