teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 3.0

    enable_button: 9  # L2 shoulder button
    enable_turbo_button: 10  # L1 shoulder button